todo_app/app.py
from flask import Flask

from todo_app.app_config import Config
from todo_app.routes import todo


def create_app():
    app = Flask(__name__)
    app.config.from_object(Config())
    app.register_blueprint(todo)
    return app

if __name__ == '__main__':
    create_app().run()

todo_app/routes.py
from flask import render_template, request, redirect, url_for, Blueprint

from todo_app.data import trello_items as trello
from todo_app.view_model import ViewModel

todo = Blueprint('todo', __name__)

@todo.route('/')
def index():
    items = trello.get_items()
    return render_template('index.html', model=ViewModel(items))

@todo.route('/items/new', methods=['POST'])
def add_item():
    name = request.form['name']
    trello.add_item(name)
    return redirect(url_for('todo.index'))

@todo.route('/items/<id>/start')
def start_item(id):
    trello.start_item(id)
    return redirect(url_for('todo.index'))

@todo.route('/items/<id>/complete')
def complete_item(id):
    trello.complete_item(id)
    return redirect(url_for('todo.index'))

@todo.route('/items/<id>/uncomplete')
def uncomplete_item(id):
    trello.uncomplete_item(id)
    return redirect(url_for('todo.index'))

todo_app/templates/index.html
{% extends "layout.html" %}

{% macro display_item(item) -%}
<li class="list-group-item" data-test-class="task">
  <div class="d-flex w-100 justify-content-between">
    <h5 class="mb-1">{{ item.name }}</h5>
    {% if item.status == 'Done' %}
      {% set badge_style = 'badge-success' %}
    {% elif item.status == 'To Do' %}
      {% set badge_style = 'badge-secondary' %}
    {% else %}
      {% set badge_style = 'badge-primary' %}
    {% endif %}
    <div><span class="badge {{ badge_style }}">{{ item.status }}</span></div>
  </div>
  {% if item.status == 'Done' %}
    <a href="{{ url_for('todo.uncomplete_item', id=item.id) }}" class="btn btn-sm btn-secondary">Mark as Incomplete</a>
  {% elif item.status == 'To Do' %}
    <a href="{{ url_for('todo.start_item', id=item.id) }}" class="btn btn-sm btn-success">Start</a>
  {% else %}
    <a href="{{ url_for('todo.complete_item', id=item.id) }}" class="btn btn-sm btn-primary">Complete</a>
  {% endif %}
</li>
{%- endmacro %}

{% macro display_item_list(title, items, test_id) -%}
<div class="row">
  <div class="col-md-12" data-test-id="{{ test_id }}">
    <h2>{{ title }}</h2>
    <ul class="list-group mb-4">
      {% for item in items %}
        {{ display_item(item) }}
      {% endfor %}
    </ul>
  </div>
</div>
{%- endmacro %}

{% block title %}To-Do App{% endblock %}

{% block content %}
  <div class="jumbotron">
    <h1 class="display-4">To-Do App</h1>
    <p class="lead">Just another to-do app.</p>
  </div>

  <div class="row">
    <div class="col-md-12">
      <h2>New item</h2>
      <form action="{{ url_for('todo.add_item') }}" method="POST">
        <div class="form-group form-row align-items-center">
          <div class="col">
            <input type="text" name="name" id="name-input" class="form-control" placeholder="Name" aria-label="Name" data-test-id="name-input">
          </div>
          <div class="col-auto">
            <button type="submit" class="btn btn-success">Add Item</button>
          </div>
        </div>
      </form>
    </div>
  </div>

  {{ display_item_list('To Do', model.to_do_items, 'to-do-section') }}
  {{ display_item_list('Doing', model.doing_items, 'doing-section') }}

  {% if model.show_all_done_items %}
    {{ display_item_list('Done', model.done_items, 'done-section') }}
  {% else %}
    {{ display_item_list('Recently Completed', model.recent_done_items, 'recently-done-section') }}
    <details>
      {{ display_item_list('', model.older_done_items, 'older-done-section') }}
      <summary>Older Tasks</summary>
    </details>
  {% endif %}

{% endblock %}

todo_app/templates/layout.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>{% block title %}To-Do App{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
      <a class="navbar-brand" href="/">To-Do App</a>
    </nav>

    <div class="container body-content">
      {% block content %}{% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>